language: node_js
node_js: stable

# S: Build Lifecycle
install:

#before_script:
  - source ./deploy.sh

script:
  - xandeerBuild

after_script:
  - npm publish
# E: Build LifeCycle

branches:
  only:
    - dev
    - master

env:
 global:
    - GH_REF: github.com/xandeer/vue-circle-choice.git
